SystemOrganization addCategory: #SocialNetwork!
SystemOrganization addCategory: 'SocialNetwork-Core'!
SystemOrganization addCategory: 'SocialNetwork-Gmail'!
SystemOrganization addCategory: 'SocialNetwork-GoogleContacts'!
SystemOrganization addCategory: 'SocialNetwork-GooglePeople'!
SystemOrganization addCategory: 'SocialNetwork-Private'!
SystemOrganization addCategory: 'SocialNetwork-Specification'!
