generated
scopes
	^ OrderedCollection withAll: #(
		'https://www.googleapis.com/auth/contacts.readonly'
		'https://www.googleapis.com/auth/plus.login'
		'https://www.googleapis.com/auth/user.addresses.read'
		'https://www.googleapis.com/auth/contacts'
		'https://www.googleapis.com/auth/userinfo.email'
		'https://www.googleapis.com/auth/user.birthday.read'
		'https://www.googleapis.com/auth/user.emails.read'
		'https://www.googleapis.com/auth/user.phonenumbers.read'
		'https://www.googleapis.com/auth/userinfo.profile'
	)
