as yet unclassified
mailChimpHtmlQuotedPrintable
	^ '<!doctype html>

<html xmlns=3D"http://www.w3.org/1999/xhtml" xmlns:v=3D"urn:schemas-micros=

oft-com:vml" xmlns:o=3D"urn:schemas-microsoft-com:office:office">

=09<head>

=09=09<!-- NAME: 1 COLUMN -->

=09=09<!--[if gte mso 15]>

=09=09<xml>

=09=09=09<o:OfficeDocumentSettings>

=09=09=09<o:AllowPNG/>

=09=09=09<o:PixelsPerInch>96</o:PixelsPerInch>

=09=09=09</o:OfficeDocumentSettings>

=09=09</xml>

=09=09<![endif]-->

=09=09<meta charset=3D"UTF-8">

        <meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3Dedge">

        <meta name=3D"viewport" content=3D"width=3Ddevice-width=2C initial=

-scale=3D1">

=09=09<title>Thank you for your support!</title>



    <style type=3D"text/css">

=09=09p{

=09=09=09margin:10px 0;

=09=09=09padding:0;

=09=09}

=09=09table{

=09=09=09border-collapse:collapse;

=09=09}

=09=09h1=2Ch2=2Ch3=2Ch4=2Ch5=2Ch6{

=09=09=09display:block;

=09=09=09margin:0;

=09=09=09padding:0;

=09=09}

=09=09img=2Ca img{

=09=09=09border:0;

=09=09=09height:auto;

=09=09=09outline:none;

=09=09=09text-decoration:none;

=09=09}

=09=09body=2C#bodyTable=2C#bodyCell{

=09=09=09height:100%;

=09=09=09margin:0;

=09=09=09padding:0;

=09=09=09width:100%;

=09=09}

=09=09#outlook a{

=09=09=09padding:0;

=09=09}

=09=09img{

=09=09=09-ms-interpolation-mode:bicubic;

=09=09}

=09=09table{

=09=09=09mso-table-lspace:0pt;

=09=09=09mso-table-rspace:0pt;

=09=09}

=09=09.ReadMsgBody{

=09=09=09width:100%;

=09=09}

=09=09.ExternalClass{

=09=09=09width:100%;

=09=09}

=09=09p=2Ca=2Cli=2Ctd=2Cblockquote{

=09=09=09mso-line-height-rule:exactly;

=09=09}

=09=09a[href^=3Dtel]=2Ca[href^=3Dsms]{

=09=09=09color:inherit;

=09=09=09cursor:default;

=09=09=09text-decoration:none;

=09=09}

=09=09p=2Ca=2Cli=2Ctd=2Cbody=2Ctable=2Cblockquote{

=09=09=09-ms-text-size-adjust:100%;

=09=09=09-webkit-text-size-adjust:100%;

=09=09}

=09=09.ExternalClass=2C.ExternalClass p=2C.ExternalClass td=2C.ExternalCla=

ss div=2C.ExternalClass span=2C.ExternalClass font{

=09=09=09line-height:100%;

=09=09}

=09=09a[x-apple-data-detectors]{

=09=09=09color:inherit !important;

=09=09=09text-decoration:none !important;

=09=09=09font-size:inherit !important;

=09=09=09font-family:inherit !important;

=09=09=09font-weight:inherit !important;

=09=09=09line-height:inherit !important;

=09=09}

=09=09#bodyCell{

=09=09=09padding:10px;

=09=09}

=09=09.templateContainer{

=09=09=09max-width:600px !important;

=09=09}

=09=09a.mcnButton{

=09=09=09display:block;

=09=09}

=09=09.mcnImage{

=09=09=09vertical-align:bottom;

=09=09}

=09=09.mcnTextContent{

=09=09=09word-break:break-word;

=09=09}

=09=09.mcnTextContent img{

=09=09=09height:auto !important;

=09=09}

=09=09.mcnDividerBlock{

=09=09=09table-layout:fixed !important;

=09=09}

=09=09body=2C#bodyTable{

=09=09=09background-color:#FAFAFA;

=09=09}

=09=09#bodyCell{

=09=09=09border-top:0;

=09=09}

=09=09.templateContainer{

=09=09=09border:0;

=09=09}

=09=09h1{

=09=09=09color:#202020;

=09=09=09font-family:Helvetica;

=09=09=09font-size:26px;

=09=09=09font-style:normal;

=09=09=09font-weight:bold;

=09=09=09line-height:125%;

=09=09=09letter-spacing:normal;

=09=09=09text-align:left;

=09=09}

=09=09h2{

=09=09=09color:#202020;

=09=09=09font-family:Helvetica;

=09=09=09font-size:22px;

=09=09=09font-style:normal;

=09=09=09font-weight:bold;

=09=09=09line-height:125%;

=09=09=09letter-spacing:normal;

=09=09=09text-align:left;

=09=09}

=09=09h3{

=09=09=09color:#202020;

=09=09=09font-family:Helvetica;

=09=09=09font-size:20px;

=09=09=09font-style:normal;

=09=09=09font-weight:bold;

=09=09=09line-height:125%;

=09=09=09letter-spacing:normal;

=09=09=09text-align:left;

=09=09}

=09=09h4{

=09=09=09color:#202020;

=09=09=09font-family:Helvetica;

=09=09=09font-size:18px;

=09=09=09font-style:normal;

=09=09=09font-weight:bold;

=09=09=09line-height:125%;

=09=09=09letter-spacing:normal;

=09=09=09text-align:left;

=09=09}

=09=09#templatePreheader{

=09=09=09background-color:#FAFAFA;

=09=09=09border-top:0;

=09=09=09border-bottom:0;

=09=09=09padding-top:9px;

=09=09=09padding-bottom:9px;

=09=09}

=09=09#templatePreheader .mcnTextContent=2C#templatePreheader .mcnTextCont=

ent p{

=09=09=09color:#656565;

=09=09=09font-family:Helvetica;

=09=09=09font-size:12px;

=09=09=09line-height:150%;

=09=09=09text-align:left;

=09=09}

=09=09#templatePreheader .mcnTextContent a=2C#templatePreheader .mcnTextCo=

ntent p a{

=09=09=09color:#656565;

=09=09=09font-weight:normal;

=09=09=09text-decoration:underline;

=09=09}

=09=09#templateHeader{

=09=09=09background-color:#FFFFFF;

=09=09=09border-top:0;

=09=09=09border-bottom:0;

=09=09=09padding-top:9px;

=09=09=09padding-bottom:0;

=09=09}

=09=09#templateHeader .mcnTextContent=2C#templateHeader .mcnTextContent p{

=09=09=09color:#202020;

=09=09=09font-family:Helvetica;

=09=09=09font-size:16px;

=09=09=09line-height:150%;

=09=09=09text-align:left;

=09=09}

=09=09#templateHeader .mcnTextContent a=2C#templateHeader .mcnTextContent=

 p a{

=09=09=09color:#2BAADF;

=09=09=09font-weight:normal;

=09=09=09text-decoration:underline;

=09=09}

=09=09#templateBody{

=09=09=09background-color:#FFFFFF;

=09=09=09border-top:0;

=09=09=09border-bottom:2px solid #EAEAEA;

=09=09=09padding-top:0;

=09=09=09padding-bottom:9px;

=09=09}

=09=09#templateBody .mcnTextContent=2C#templateBody .mcnTextContent p{

=09=09=09color:#202020;

=09=09=09font-family:Helvetica;

=09=09=09font-size:16px;

=09=09=09line-height:150%;

=09=09=09text-align:left;

=09=09}

=09=09#templateBody .mcnTextContent a=2C#templateBody .mcnTextContent p a{

=09=09=09color:#2BAADF;

=09=09=09font-weight:normal;

=09=09=09text-decoration:underline;

=09=09}

=09=09#templateFooter{

=09=09=09background-color:#FAFAFA;

=09=09=09border-top:0;

=09=09=09border-bottom:0;

=09=09=09padding-top:9px;

=09=09=09padding-bottom:9px;

=09=09}

=09=09#templateFooter .mcnTextContent=2C#templateFooter .mcnTextContent p{

=09=09=09color:#656565;

=09=09=09font-family:Helvetica;

=09=09=09font-size:12px;

=09=09=09line-height:150%;

=09=09=09text-align:center;

=09=09}

=09=09#templateFooter .mcnTextContent a=2C#templateFooter .mcnTextContent=

 p a{

=09=09=09color:#656565;

=09=09=09font-weight:normal;

=09=09=09text-decoration:underline;

=09=09}

=09@media only screen and (min-width:768px){

=09=09.templateContainer{

=09=09=09width:600px !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09body=2Ctable=2Ctd=2Cp=2Ca=2Cli=2Cblockquote{

=09=09=09-webkit-text-size-adjust:none !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09body{

=09=09=09width:100% !important;

=09=09=09min-width:100% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09#bodyCell{

=09=09=09padding-top:10px !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnImage{

=09=09=09width:100% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnShareContent=2C.mcnCaptionTopContent=2C.mcnCaptionBottomContent=

=2C.mcnTextContentContainer=2C.mcnBoxedTextContentContainer=2C.mcnImageGro=

upContentContainer=2C.mcnCaptionLeftTextContentContainer=2C.mcnCaptionRigh=

tTextContentContainer=2C.mcnCaptionLeftImageContentContainer=2C.mcnCaption=

RightImageContentContainer=2C.mcnImageCardLeftTextContentContainer=2C.mcnI=

mageCardRightTextContentContainer{

=09=09=09max-width:100% !important;

=09=09=09width:100% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnBoxedTextContentContainer{

=09=09=09min-width:100% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnImageGroupContent{

=09=09=09padding:9px !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnCaptionLeftContentOuter .mcnTextContent=2C.mcnCaptionRightConten=

tOuter .mcnTextContent{

=09=09=09padding-top:9px !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnImageCardTopImageContent=2C.mcnCaptionBlockInner .mcnCaptionTopC=

ontent:last-child .mcnTextContent{

=09=09=09padding-top:18px !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnImageCardBottomImageContent{

=09=09=09padding-bottom:9px !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnImageGroupBlockInner{

=09=09=09padding-top:0 !important;

=09=09=09padding-bottom:0 !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnImageGroupBlockOuter{

=09=09=09padding-top:9px !important;

=09=09=09padding-bottom:9px !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnTextContent=2C.mcnBoxedTextContentColumn{

=09=09=09padding-right:18px !important;

=09=09=09padding-left:18px !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnImageCardLeftImageContent=2C.mcnImageCardRightImageContent{

=09=09=09padding-right:18px !important;

=09=09=09padding-bottom:0 !important;

=09=09=09padding-left:18px !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcpreview-image-uploader{

=09=09=09display:none !important;

=09=09=09width:100% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09h1{

=09=09=09font-size:22px !important;

=09=09=09line-height:125% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09h2{

=09=09=09font-size:20px !important;

=09=09=09line-height:125% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09h3{

=09=09=09font-size:18px !important;

=09=09=09line-height:125% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09h4{

=09=09=09font-size:16px !important;

=09=09=09line-height:150% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09.mcnBoxedTextContentContainer .mcnTextContent=2C.mcnBoxedTextContent=

Container .mcnTextContent p{

=09=09=09font-size:14px !important;

=09=09=09line-height:150% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09#templatePreheader{

=09=09=09display:block !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09#templatePreheader .mcnTextContent=2C#templatePreheader .mcnTextCont=

ent p{

=09=09=09font-size:14px !important;

=09=09=09line-height:150% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09#templateHeader .mcnTextContent=2C#templateHeader .mcnTextContent p{

=09=09=09font-size:16px !important;

=09=09=09line-height:150% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09#templateBody .mcnTextContent=2C#templateBody .mcnTextContent p{

=09=09=09font-size:16px !important;

=09=09=09line-height:150% !important;

=09=09}



}=09@media only screen and (max-width: 480px){

=09=09#templateFooter .mcnTextContent=2C#templateFooter .mcnTextContent p{

=09=09=09font-size:14px !important;

=09=09=09line-height:150% !important;

=09=09}



}</style></head>

    <body style=3D"height: 100%;margin: 0;padding: 0;width: 100%;-ms-text-=

size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #FAFAFA=

;">

        <center>

            <table align=3D"center" border=3D"0" cellpadding=3D"0" cellspa=

cing=3D"0" height=3D"100%" width=3D"100%" id=3D"bodyTable" style=3D"border=

-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-s=

ize-adjust: 100%;-webkit-text-size-adjust: 100%;height: 100%;margin: 0;pad=

ding: 0;width: 100%;background-color: #FAFAFA;">

                <tr>

                    <td align=3D"center" valign=3D"top" id=3D"bodyCell" st=

yle=3D"mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-te=

xt-size-adjust: 100%;height: 100%;margin: 0;padding: 10px;width: 100%;bord=

er-top: 0;">

                        <!-- BEGIN TEMPLATE // -->

=09=09=09=09=09=09<!--[if gte mso 9]>

=09=09=09=09=09=09<table align=3D"center" border=3D"0" cellspacing=3D"0" c=

ellpadding=3D"0" width=3D"600" style=3D"width:600px;">

=09=09=09=09=09=09<tr>

=09=09=09=09=09=09<td align=3D"center" valign=3D"top" width=3D"600" style=

=3D"width:600px;">

=09=09=09=09=09=09<![endif]-->

                        <table border=3D"0" cellpadding=3D"0" cellspacing=

=3D"0" width=3D"100%" class=3D"templateContainer" style=3D"border-collapse=

: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjus=

t: 100%;-webkit-text-size-adjust: 100%;border: 0;max-width: 600px !importa=

nt;">

                            <tr>

                                <td valign=3D"top" id=3D"templatePreheader=

" style=3D"mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webki=

t-text-size-adjust: 100%;background-color: #FAFAFA;border-top: 0;border-bo=

ttom: 0;padding-top: 9px;padding-bottom: 9px;"><table class=3D"mcnTextBloc=

k" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" style=

=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;=

-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">

    <tbody class=3D"mcnTextBlockOuter">

        <tr>

            <td class=3D"mcnTextBlockInner" valign=3D"top" style=3D"mso-li=

ne-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjus=

t: 100%;">



                <table class=3D"mcnTextContentContainer" border=3D"0" cell=

padding=3D"0" cellspacing=3D"0" width=3D"366" align=3D"left" style=3D"bord=

er-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text=

-size-adjust: 100%;-webkit-text-size-adjust: 100%;">

                    <tbody><tr>



                        <td class=3D"mcnTextContent" style=3D"padding-top:=

 9px;padding-left: 18px;padding-bottom: 9px;padding-right: 0;mso-line-heig=

ht-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%=

;word-break: break-word;color: #656565;font-family: Helvetica;font-size: 1=

2px;line-height: 150%;text-align: left;" valign=3D"top">



                            Thank you for your support! Sign up for import=

ant updates.

                        </td>

                    </tr>

                </tbody></table>



                <table class=3D"mcnTextContentContainer" border=3D"0" cell=

padding=3D"0" cellspacing=3D"0" width=3D"197" align=3D"right" style=3D"bor=

der-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-tex=

t-size-adjust: 100%;-webkit-text-size-adjust: 100%;">

                    <tbody><tr>



                        <td class=3D"mcnTextContent" style=3D"padding-top:=

 9px;padding-right: 18px;padding-bottom: 9px;padding-left: 0;mso-line-heig=

ht-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%=

;word-break: break-word;color: #656565;font-family: Helvetica;font-size: 1=

2px;line-height: 150%;text-align: left;" valign=3D"top">



                            

                        </td>

                    </tr>

                </tbody></table>



            </td>

        </tr>

    </tbody>

</table></td>

                            </tr>

                            <tr>

                                <td valign=3D"top" id=3D"templateHeader" s=

tyle=3D"mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-t=

ext-size-adjust: 100%;background-color: #FFFFFF;border-top: 0;border-botto=

m: 0;padding-top: 9px;padding-bottom: 0;"><table class=3D"mcnImageBlock" s=

tyle=3D"min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;ms=

o-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 1=

00%;" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%">

    <tbody class=3D"mcnImageBlockOuter">

            <tr>

                <td style=3D"padding: 9px;mso-line-height-rule: exactly;-m=

s-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class=3D"mcnImag=

eBlockInner" valign=3D"top">

                    <table class=3D"mcnImageContentContainer" style=3D"min=

-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rsp=

ace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" borde=

r=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" align=3D"left">

                        <tbody><tr>

                            <td class=3D"mcnImageContent" style=3D"padding=

-right: 9px;padding-left: 9px;padding-top: 0;padding-bottom: 0;text-align:=

 center;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-t=

ext-size-adjust: 100%;" valign=3D"top">





                                        <img alt=3D"" src=3D"https://galle=

ry.mailchimp.com/ab40fa6dcb43014485155dc82/images/12565f91-4c7d-4497-b09e-=

c33ccb481eca.jpg" style=3D"max-width: 800px;padding-bottom: 0;display: inl=

ine !important;vertical-align: bottom;border: 0;height: auto;outline: none=

;text-decoration: none;-ms-interpolation-mode: bicubic;" class=3D"mcnImage=

" width=3D"564" align=3D"middle">





                            </td>

                        </tr>

                    </tbody></table>

                </td>

            </tr>

    </tbody>

</table></td>

                            </tr>

                            <tr>

                                <td valign=3D"top" id=3D"templateBody" sty=

le=3D"mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-tex=

t-size-adjust: 100%;background-color: #FFFFFF;border-top: 0;border-bottom:=

 2px solid #EAEAEA;padding-top: 0;padding-bottom: 9px;"><table class=3D"mc=

nTextBlock" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%=

" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspac=

e: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">

    <tbody class=3D"mcnTextBlockOuter">

        <tr>

            <td class=3D"mcnTextBlockInner" valign=3D"top" style=3D"mso-li=

ne-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjus=

t: 100%;">



                <table class=3D"mcnTextContentContainer" border=3D"0" cell=

padding=3D"0" cellspacing=3D"0" width=3D"100%" align=3D"left" style=3D"bor=

der-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-tex=

t-size-adjust: 100%;-webkit-text-size-adjust: 100%;">

                    <tbody><tr>



                        <td class=3D"mcnTextContent" style=3D"padding-top:=

 9px;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-line-h=

eight-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 1=

00%;word-break: break-word;color: #202020;font-family: Helvetica;font-size=

: 16px;line-height: 150%;text-align: left;" valign=3D"top">



                            <h1 style=3D"display: block;margin: 0;padding:=
 0;color: #202020;font-family: Helvetica;font-size: 26px;font-style: norma=
l;font-weight: bold;line-height: 125%;letter-spacing: normal;text-align: l=
eft;">Thank you for your leadership.</h1>

<p style=3D"margin: 10px 0;padding: 0;mso-line-height-rule: exactly;-ms-te=
xt-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #202020;font-fa=
mily: Helvetica;font-size: 16px;line-height: 150%;text-align: left;">Last=
 week=2C you joined more than 1=2C000 citizens who stood up to ensure that=
 the&nbsp;New Rochelle Fire Department is prepared to safely protect our N=
R Future.<br>
<br>
We appreciated it all - from Facebook "Likes" and "Shares" to all the pers=
onal messages. But you... By taking the extra time to submit an official c=
omment=2C you lead the charge! Our 80+ official comments have put on recor=
d our citizens'' recognition of the impact of downtown development on the f=
ire department. As the developers address your comment=2C as required by l=
aw=2C you will have supported them in making our NR future both prosperous=
 <em>and safe</em>.<br>
<br>
As an advocate for public safety=2C we''d like to keep you in the loop - fr=
om important safety bulletins to community news you won''t want to miss...</p>

<table style=3D"background-color: #58598E;border-radius: 5px;border-collap=
se: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adj=
ust: 100%;-webkit-text-size-adjust: 100%;" border=3D"0" cellpadding=3D"0"=
 cellspacing=3D"0" width=3D"100%">
=09<tbody>
=09=09<tr>
=09=09=09<td style=3D"color: #ffffff;font-family: Helvetica=2C Arial=2C sa=
ns-serif;font-size: 16px;font-weight: bold;letter-spacing: -.5px;line-heig=
ht: 150%;padding: 15px 30px 15px 30px;text-align: center;mso-line-height-r=
ule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" v=
align=3D"middle" align=3D"center"><a href=3D"', self newsletterUrl asString encodeQuotedPrintable, '" style=3D"=
color: #ffffff;text-decoration: none;mso-line-height-rule: exactly;-ms-tex=
t-size-adjust: 100%;-webkit-text-size-adjust: 100%;font-weight: normal;" t=
arget=3D"_blank">Sign Up for Our Newsletter</a></td>
=09=09</tr>
=09</tbody>
</table>

                        </td>
                    </tr>
                </tbody></table>

            </td>
        </tr>
    </tbody>
</table></td>
                            </tr>
                            <tr>
                                <td valign=3D"top" id=3D"templateFooter" s=
tyle=3D"mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-t=
ext-size-adjust: 100%;background-color: #FAFAFA;border-top: 0;border-botto=
m: 0;padding-top: 9px;padding-bottom: 9px;"><table class=3D"mcnFollowBlock=
" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" style=3D=
"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms=
-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
    <tbody class=3D"mcnFollowBlockOuter">
        <tr>
            <td style=3D"padding: 9px;mso-line-height-rule: exactly;-ms-te=
xt-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class=3D"mcnFollowBl=
ockInner" valign=3D"top" align=3D"center">
                <table class=3D"mcnFollowContentContainer" border=3D"0" ce=
llpadding=3D"0" cellspacing=3D"0" width=3D"100%" style=3D"border-collapse:=
 collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust=
: 100%;-webkit-text-size-adjust: 100%;">
    <tbody><tr>
        <td style=3D"padding-left: 9px;padding-right: 9px;mso-line-height-=
rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"=
 align=3D"center">
            <table class=3D"mcnFollowContent" border=3D"0" cellpadding=3D"=
0" cellspacing=3D"0" width=3D"100%" style=3D"border-collapse: collapse;mso=
-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webki=
t-text-size-adjust: 100%;">
                <tbody><tr>
                    <td style=3D"padding-top: 9px;padding-right: 9px;paddi=
ng-left: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-web=
kit-text-size-adjust: 100%;" valign=3D"top" align=3D"center">
                        <table border=3D"0" cellpadding=3D"0" cellspacing=
=3D"0" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-=
rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                            <tbody><tr>
                                <td valign=3D"top" style=3D"mso-line-heigh=
t-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;=
">
                                    <!--[if mso]>
                                    <table align=3D"left" border=3D"0" cel=
lspacing=3D"0" cellpadding=3D"0" width=3D"524">
                                    <tr>
                                    <td align=3D"left" valign=3D"top" widt=
h=3D"524">
                                    <![endif]-->



                                            <table border=3D"0" cellpaddin=
g=3D"0" cellspacing=3D"0" align=3D"left" style=3D"border-collapse: collaps=
e;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-=
webkit-text-size-adjust: 100%;">
                                                <tbody><tr>
                                                    <td style=3D"padding-r=
ight: 10px;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size=
-adjust: 100%;-webkit-text-size-adjust: 100%;" class=3D"mcnFollowContentIt=
emContainer" valign=3D"top">
                                                        <table class=3D"mc=
nFollowContentItem" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=
=3D"100%" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-tab=
le-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"=
>
                                                            <tbody><tr>
                                                                <td style=
=3D"padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left:=
 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text=
-size-adjust: 100%;" valign=3D"middle" align=3D"left">
                                                                    <table=
 border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"" align=3D"left=
" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspac=
e: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                                                        <t=
body><tr>

                                                                         =
       <td class=3D"mcnFollowIconContent" valign=3D"middle" width=3D"24" a=
lign=3D"center" style=3D"mso-line-height-rule: exactly;-ms-text-size-adjus=
t: 100%;-webkit-text-size-adjust: 100%;">
                                                                         =
           <a href=3D"https://twitter.com/NewRochelleFire" target=3D"_blan=
k" style=3D"mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webk=
it-text-size-adjust: 100%;"><img src=3D"http://cdn-images.mailchimp.com/ic=
ons/social-block-v2/color-twitter-48.png" style=3D"display: block;border:=
 0;height: auto;outline: none;text-decoration: none;-ms-interpolation-mode=
: bicubic;" class=3D"" height=3D"24" width=3D"24"></a>
                                                                         =
       </td>


                                                                        </=
tr>
                                                                    </tbod=
y></table>
                                                                </td>
                                                            </tr>
                                                        </tbody></table>
                                                    </td>
                                                </tr>
                                            </tbody></table>




                                            <table border=3D"0" cellpaddin=
g=3D"0" cellspacing=3D"0" align=3D"left" style=3D"border-collapse: collaps=
e;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-=
webkit-text-size-adjust: 100%;">
                                                <tbody><tr>
                                                    <td style=3D"padding-r=
ight: 10px;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size=
-adjust: 100%;-webkit-text-size-adjust: 100%;" class=3D"mcnFollowContentIt=
emContainer" valign=3D"top">
                                                        <table class=3D"mc=
nFollowContentItem" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=
=3D"100%" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-tab=
le-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"=
>
                                                            <tbody><tr>
                                                                <td style=
=3D"padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left:=
 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text=
-size-adjust: 100%;" valign=3D"middle" align=3D"left">
                                                                    <table=
 border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"" align=3D"left=
" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspac=
e: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                                                        <t=
body><tr>

                                                                         =
       <td class=3D"mcnFollowIconContent" valign=3D"middle" width=3D"24" a=
lign=3D"center" style=3D"mso-line-height-rule: exactly;-ms-text-size-adjus=
t: 100%;-webkit-text-size-adjust: 100%;">
                                                                         =
           <a href=3D"https://www.facebook.com/NewRochelleUFFA" target=3D"=
_blank" style=3D"mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;=
-webkit-text-size-adjust: 100%;"><img src=3D"http://cdn-images.mailchimp.c=
om/icons/social-block-v2/color-facebook-48.png" style=3D"display: block;bo=
rder: 0;height: auto;outline: none;text-decoration: none;-ms-interpolation=
-mode: bicubic;" class=3D"" height=3D"24" width=3D"24"></a>
                                                                         =
       </td>


                                                                        </=
tr>
                                                                    </tbod=
y></table>
                                                                </td>
                                                            </tr>
                                                        </tbody></table>
                                                    </td>
                                                </tr>
                                            </tbody></table>




                                            <table border=3D"0" cellpaddin=
g=3D"0" cellspacing=3D"0" align=3D"left" style=3D"border-collapse: collaps=
e;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-=
webkit-text-size-adjust: 100%;">
                                                <tbody><tr>
                                                    <td style=3D"padding-r=
ight: 0;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size-ad=
just: 100%;-webkit-text-size-adjust: 100%;" class=3D"mcnFollowContentItemC=
ontainer" valign=3D"top">
                                                        <table class=3D"mc=
nFollowContentItem" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=
=3D"100%" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-tab=
le-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"=
>
                                                            <tbody><tr>
                                                                <td style=
=3D"padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left:=
 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text=
-size-adjust: 100%;" valign=3D"middle" align=3D"left">
                                                                    <table=
 border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"" align=3D"left=
" style=3D"border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspac=
e: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                                                        <t=
body><tr>

                                                                         =
       <td class=3D"mcnFollowIconContent" valign=3D"middle" width=3D"24" a=
lign=3D"center" style=3D"mso-line-height-rule: exactly;-ms-text-size-adjus=
t: 100%;-webkit-text-size-adjust: 100%;">
                                                                         =
           <a href=3D"http://newrochellefirefighters.org/" target=3D"_blan=
k" style=3D"mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webk=
it-text-size-adjust: 100%;"><img src=3D"http://cdn-images.mailchimp.com/ic=
ons/social-block-v2/color-link-48.png" style=3D"display: block;border: 0;h=
eight: auto;outline: none;text-decoration: none;-ms-interpolation-mode: bi=
cubic;" class=3D"" height=3D"24" width=3D"24"></a>
                                                                         =
       </td>


                                                                        </=
tr>
                                                                    </tbod=
y></table>
                                                                </td>
                                                            </tr>
                                                        </tbody></table>
                                                    </td>
                                                </tr>
                                            </tbody></table>


                                    <!--[if mso]>
                                    </td>
                                    </tr>
                                    </table>
                                    <![endif]-->
                                </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
            </tbody></table>
        </td>
    </tr>
</tbody></table>

            </td>
        </tr>
    </tbody>
</table><table class=3D"mcnDividerBlock" style=3D"min-width: 100%;border-c=
ollapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-siz=
e-adjust: 100%;-webkit-text-size-adjust: 100%;table-layout: fixed !importa=
nt;" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%">
    <tbody class=3D"mcnDividerBlockOuter">
        <tr>
            <td class=3D"mcnDividerBlockInner" style=3D"min-width: 100%;pa=
dding: 10px 18px 25px;mso-line-height-rule: exactly;-ms-text-size-adjust:=
 100%;-webkit-text-size-adjust: 100%;">
                <table class=3D"mcnDividerContent" style=3D"min-width: 100=
%;border-top: 2px solid #EEEEEE;border-collapse: collapse;mso-table-lspace=
: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-a=
djust: 100%;" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"10=
0%">
                    <tbody><tr>
                        <td style=3D"mso-line-height-rule: exactly;-ms-tex=
t-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                            <span></span>
                        </td>
                    </tr>
                </tbody></table>
<!--
                <td class=3D"mcnDividerBlockInner" style=3D"padding: 18px;=
">
                <hr class=3D"mcnDividerContent" style=3D"border-bottom-col=
or:none; border-left-color:none; border-right-color:none; border-bottom-wi=
dth:0; border-left-width:0; border-right-width:0; margin-top:0; margin-rig=
ht:0; margin-bottom:0; margin-left:0;" />
-->
            </td>
        </tr>
    </tbody>
</table><table class=3D"mcnTextBlock" border=3D"0" cellpadding=3D"0" cells=
pacing=3D"0" width=3D"100%" style=3D"border-collapse: collapse;mso-table-l=
space: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-s=
ize-adjust: 100%;">
    <tbody class=3D"mcnTextBlockOuter">
        <tr>
            <td class=3D"mcnTextBlockInner" valign=3D"top" style=3D"mso-li=
ne-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjus=
t: 100%;">

                <table class=3D"mcnTextContentContainer" border=3D"0" cell=
padding=3D"0" cellspacing=3D"0" width=3D"100%" align=3D"left" style=3D"bor=
der-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-tex=
t-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                    <tbody><tr>

                        <td class=3D"mcnTextContent" style=3D"padding-top:=
 9px;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-line-h=
eight-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 1=
00%;word-break: break-word;color: #656565;font-family: Helvetica;font-size=
: 12px;line-height: 150%;text-align: center;" valign=3D"top">

                            <em>Copyright =A9 2015 New Rochelle Uniform=
ed Firefighters Association=2C All rights reserved.</em>
<br>
    You are receiving this email because you cc''d us on your official comm=
ent regarding New Rochelle''s downtown development.
    <br>
    <br>
    <strong>Our mailing address is:</strong>
    <br>
    <div class=3D"vcard"><span class=3D"org fn">New Rochelle Uniformed Fir=
efighters Association</span><div class=3D"adr"><div class=3D"street-addres=
s">PO Box 944</div><span class=3D"locality">New Rochelle</span>=2C <span c=
lass=3D"region">NY</span>  <span class=3D"postal-code">10802</span></div><=
br><a href=3D"http://facebook.us11.list-manage.com/vcard?u=3Dab40fa6dcb43014485155dc82&i=
d=3D7de9885081" class=3D"hcard-download">Add us to your add=
ress book</a></div>

    <br>

    <br>

                        </td>

                    </tr>

                </tbody></table>



            </td>

        </tr>

    </tbody>

</table></td>

                            </tr>

                        </table>

=09=09=09=09=09=09<!--[if gte mso 9]>

=09=09=09=09=09=09</td>

=09=09=09=09=09=09</tr>

=09=09=09=09=09=09</table>

=09=09=09=09=09=09<![endif]-->

                        <!-- // END TEMPLATE -->

                    </td>

                </tr>

            </table>

        </center>

    </body>

</html>'