as yet unclassified
mailChimpPlainTextPart
	^ 'Thank you for your support! Sign up for important updates.


** Thank you for your leadership.
------------------------------------------------------------

Last week, you joined more than 1,000 citizens who stood up to ensure that the New Rochelle Fire Department is prepared to safely protect our NR Future.

We appreciated it all - from Facebook "Likes" and "Shares" to all the personal messages. But you... By taking the extra time to submit an official comment, you lead the charge! Our 80+ official comments have put on record our citizens'' recognition of the impact of downtown development on the fire department. As the developers address your comment, as required by law, you will have supported them in making our NR future both prosperous and safe.

As an advocate for public safety, we''d like to keep you in the loop - from important safety bulletins to community news you won''t want to miss...
Sign Up for Our Newsletter (', self newsletterUrl asString, ')

============================================================

** (https://twitter.com/NewRochelleFire)
** (https://www.facebook.com/NewRochelleUFFA)
** (http://newrochellefirefighters.org/)

Copyright © 2015 New Rochelle Uniformed Firefighters Association, All rights reserved. You are receiving this email because you cc''d us on your official comment regarding New Rochelle''s downtown development.

Our mailing address is:
New Rochelle Uniformed Firefighters Association
PO Box 944
New Rochelle, NY 10802
USA'